language: cpp
os:
  - linux
  - osx
script: cmake . && make

jobs:
  include:
    - script: build/ServerCore*
    - script: build/ServerCore* tests.starcore
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: 
		  secure: $key
        skip_cleanup: true
		file_glob: true
		file: build/*
        on:
          tags: true