language: cpp
os:
  - linux
  - osx
script: 
  - sudo apt update
  - sudo apt install g++-7 -y
  - cmake . && make
  - build/StarCore*
  - build/StarCore* tests.starcore

deploy:
  provider: releases
  api_key: 
    secure: $key
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true